title: Coderic CoWorker
email: info@coderic.net
description: Corporacion Orientada al Desarrollo Estratégico de Recursos de Información Comercial
baseurl: ""
url: "https://coworker.coderic.net"
disqus: coderic
google_analytics: UA-628256-11
facebook:
    app_id: 532970243841279
    version: v3.2
twitter_username: Coderic
github_username:  Coderic
author: Coderic
logo: /images/logo43.png
lang: es
markdown: kramdown
include: [_redirects, _headers]
remote_theme: Coderic/CodericTheme
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate